#! /bin/sh
mount none /proc -t proc
mount none /sys -t sysfs
mount / -o remount,rw

# /dev
/sbin/mdev -s
echo /sbin/mdev >/proc/sys/kernel/hotplug
chmod 777 /dev/fb0

# French
loadkmap < /etc/azerty.kmap

# Network
udhcpc -i eth0 -s /etc/share/udhcpc/default.script

# Web server
httpd -h /var/www
